Update DOCS.md
hassio-addons/addon-mopidy pull request #69
Opened 2020-12-25 22:15 UTC by Nossnevs

Fixes build error

# Proposed Changes

> (Describe the changes and rationale behind them)

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

2020-12-26 13:34 UTC, frenck requested changes

2020-12-26 13:34 UTC, frenck commented on mopidy/DOCS.md
> +Allows you to specify additional [Ubuntu packages][system_packages] to be
That reference does not exist.

2020-12-28 21:49 UTC, Nossnevs commented on mopidy/DOCS.md
> +Allows you to specify additional [Ubuntu packages][system_packages] to be
Fixed in updated commit

2020-12-29 13:20 UTC, frenck approved these changes
Thanks, @Nossnevs 👍 

Happy Holidays!

2020-12-29 13:20 UTC, merged